-- Shipping address (per-user address book)
CREATE TABLE shipping_address (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    recipient_name  VARCHAR(200) NOT NULL,
    line1           VARCHAR(200) NOT NULL,
    line2           VARCHAR(200),
    city            VARCHAR(120) NOT NULL,
    postal_code     VARCHAR(20)  NOT NULL,
    country         VARCHAR(2)   NOT NULL,
    phone           VARCHAR(40),
    created_at      TIMESTAMP    NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_shipping_address_user ON shipping_address(user_id);

-- Orders
CREATE TABLE orders (
    id                            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_user_id                 BIGINT NOT NULL REFERENCES app_user(id),
    artist_user_id                BIGINT NOT NULL REFERENCES app_user(id),
    artwork_id                    BIGINT NOT NULL REFERENCES artwork(id),
    quantity                      INTEGER NOT NULL DEFAULT 1,
    status                        VARCHAR(20) NOT NULL,
    subtotal                      NUMERIC(12,2) NOT NULL,
    shipping_fee                  NUMERIC(12,2) NOT NULL,
    platform_fee                  NUMERIC(12,2) NOT NULL,
    total                         NUMERIC(12,2) NOT NULL,
    currency                      VARCHAR(3) NOT NULL DEFAULT 'EUR',
    stripe_checkout_session_id    VARCHAR(255) UNIQUE,
    stripe_payment_intent_id      VARCHAR(255),
    ship_recipient_name           VARCHAR(200) NOT NULL,
    ship_line1                    VARCHAR(200) NOT NULL,
    ship_line2                    VARCHAR(200),
    ship_city                     VARCHAR(120) NOT NULL,
    ship_postal_code              VARCHAR(20)  NOT NULL,
    ship_country                  VARCHAR(2)   NOT NULL,
    ship_phone                    VARCHAR(40),
    tracking_number               VARCHAR(100),
    shipping_carrier              VARCHAR(80),
    cancellation_reason           VARCHAR(500),
    paid_at                       TIMESTAMP,
    shipped_at                    TIMESTAMP,
    delivered_at                  TIMESTAMP,
    cancelled_at                  TIMESTAMP,
    refunded_at                   TIMESTAMP,
    created_at                    TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at                    TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_orders_buyer   ON orders(buyer_user_id);
CREATE INDEX idx_orders_artist  ON orders(artist_user_id);
CREATE INDEX idx_orders_artwork ON orders(artwork_id);
CREATE INDEX idx_orders_status  ON orders(status);

-- Webhook event dedup
CREATE TABLE stripe_webhook_event (
    id           VARCHAR(100) PRIMARY KEY,
    event_type   VARCHAR(80)  NOT NULL,
    received_at  TIMESTAMP    NOT NULL DEFAULT NOW()
);

-- Artwork: split sale_status into type + state; add edition + reservation columns
ALTER TABLE artwork ADD COLUMN sale_type            VARCHAR(20);
ALTER TABLE artwork ADD COLUMN sale_state           VARCHAR(20);
ALTER TABLE artwork ADD COLUMN edition_size         INTEGER;
ALTER TABLE artwork ADD COLUMN reserved_until       TIMESTAMP;
ALTER TABLE artwork ADD COLUMN reserved_by_user_id  BIGINT REFERENCES app_user(id);

-- Data migration from old sale_status
UPDATE artwork SET sale_type = 'ORIGINAL', sale_state = 'AVAILABLE'                     WHERE sale_status = 'ORIGINAL';
UPDATE artwork SET sale_type = 'EDITION',  sale_state = 'AVAILABLE', edition_size = 10  WHERE sale_status = 'EDITION';
UPDATE artwork SET sale_type = 'ORIGINAL', sale_state = 'AVAILABLE'                     WHERE sale_status = 'AVAILABLE';
UPDATE artwork SET sale_type = 'ORIGINAL', sale_state = 'SOLD'                          WHERE sale_status = 'SOLD';
UPDATE artwork SET sale_type = 'ORIGINAL' WHERE sale_type  IS NULL;
UPDATE artwork SET sale_state = 'DRAFT'   WHERE sale_state IS NULL;

ALTER TABLE artwork ALTER COLUMN sale_type  SET NOT NULL;
ALTER TABLE artwork ALTER COLUMN sale_state SET NOT NULL;
ALTER TABLE artwork DROP COLUMN sale_status;

CREATE INDEX idx_artwork_sale_state     ON artwork(sale_state);
CREATE INDEX idx_artwork_reserved_until ON artwork(reserved_until) WHERE reserved_until IS NOT NULL;
