spring.flyway.locations=classpath:db/migration,classpath:db/dev

spring.quartz.auto-startup=false

stripe.api-key=sk_test_FAKE
stripe.webhook-secret=whsec_test_FAKE
stripe.success-url-base=http://localhost/orders
stripe.cancel-url-base=http://localhost/orders
